import ora from 'ora'
import chalk from 'chalk'
import { existsSync } from 'fs'
import { join } from 'path'
import {
  findLoreRoot, initStore, lorePath, writeStore, appendToStore, writeDeepDecision,
  getCommits, extractFromCommits, createFileCache, parseExtractionResponse,
  type ScanDepth, type ExtractionResult
} from '@chronicle/core'
import { makeLLMProvider } from '../llm.js'
import { formatDecisionEntry, formatRejectionEntry, formatDeepADR, slugify } from '../format.js'

export async function cmdInit(opts: { depth: string; llm: string }) {
  const cwd = process.cwd()
  const depth = opts.depth as ScanDepth

  // Prevent double-init
  if (existsSync(join(cwd, '.lore'))) {
    console.log(chalk.yellow('⚠  .lore/ already exists. Run `chronicle deepen` to extend the scan.'))
    return
  }

  // Validate we're in a git repo
  if (!existsSync(join(cwd, '.git'))) {
    console.error(chalk.red('✗  Not a git repository. Run `git init` first.'))
    process.exit(1)
  }

  console.log(chalk.bold('\n◆ Chronicle — initializing\n'))

  // Phase 1: scaffold the store
  initStore(cwd)
  const spinner = ora('Scanning git history...').start()

  // Phase 2: collect commits
  const commits = getCommits(cwd, depth)
  spinner.text = `Found ${commits.length} meaningful commits — extracting decisions...`

  if (commits.length === 0) {
    spinner.warn('No meaningful commits found in this range. Try --depth=all')
    writeBootstrapPlaceholder(cwd, depth)
    return
  }

  // Phase 3: extract decisions (v1 simple strategy, cached by SHA)
  const llm = makeLLMProvider(opts.llm)
  const cache = createFileCache(cwd)
  let processed = 0

  const results = await extractFromCommits(commits, async (prompt) => {
    const result = await llm(prompt)
    processed += 6  // approximate
    spinner.text = `Processing commits... ${Math.min(processed, commits.length)}/${commits.length}`
    return result
  }, { strategy: 'simple', cache })

  // Phase 4: write to store
  spinner.text = 'Writing knowledge base...'
  buildStore(cwd, results)

  spinner.succeed(chalk.green(`Done! .lore/ initialized from ${commits.length} commits`))

  // Summary
  const decisions = results.filter(r => r.isDecision)
  const rejections = results.filter(r => r.isRejection)
  const deep = decisions.filter(r => r.isDeep)

  console.log(`
  ${chalk.bold('Knowledge base:')}
  ${chalk.cyan(decisions.length)} decisions logged
  ${chalk.red(rejections.length)} rejections captured  ${chalk.dim('← what was tried & abandoned')}
  ${chalk.yellow(deep.length)} deep ADRs generated

  ${chalk.bold('Next steps:')}
  ${chalk.dim('chronicle inject')}          — pipe context into your AI tool
  ${chalk.dim('chronicle deepen')}          — scan further back in history
  ${chalk.dim('chronicle inject | claude')} — start a Claude session with full context
  `)
}

function buildStore(root: string, results: ExtractionResult[]) {
  const decisions = results.filter(r => r.isDecision)
  const rejections = results.filter(r => r.isRejection)

  // decisions.md — lightweight index
  const tableRows = decisions.map(d =>
    `| ${d.title.slice(0, 50)} | ${d.affects.join(', ').slice(0, 40)} | ${d.risk} |${d.isDeep ? ` [→](decisions/${slugify(d.title)}.md)` : ''} |`
  ).join('\n')

  writeStore(root, 'decisions', `# Decision Log\n\n| Decision | Affects | Risk | ADR |\n|----------|---------|------|-----|\n${tableRows}\n`)

  // rejected.md — append each rejection
  for (const r of rejections) {
    appendToStore(root, 'rejected', formatRejectionEntry(r))
  }

  // deep ADR files for complex decisions
  for (const d of decisions.filter(r => r.isDeep)) {
    writeDeepDecision(root, slugify(d.title), formatDeepADR(d))
  }
}

function writeBootstrapPlaceholder(root: string, depth: ScanDepth) {
  writeStore(root, 'decisions', `# Decision Log\n\n_No commits found in depth: ${depth}. Run \`chronicle deepen --depth=all\` to scan full history._\n`)
  writeStore(root, 'index', `# Project Index\n\n_Generated by Chronicle — run \`chronicle deepen\` to populate._\n`)
}
