/**
 * chronicle migrate — upgrade .lore/ schema to the current version.
 *
 * Safe to run multiple times (idempotent). Each migration step checks
 * whether the target state already exists before writing.
 *
 * Schema versions:
 *   v1  — initial: decisions.md + rejected.md + risks.md (no index.md, no .extraction-cache.json key)
 *   v2  — index.md added (v0.6+)
 *   v3  — .extraction-cache.json renamed from .cache.json (v0.7+)
 *   v4  — low-confidence.md added, process.log bounded (v0.12+)
 *   v5  — current: evolution era deduplication, index.md always generated (v0.13)
 */

import chalk from 'chalk'
import { existsSync, readFileSync, writeFileSync, renameSync } from 'fs'
import { join } from 'path'
import { findLoreRoot, lorePath, STORE_FILES } from '@chronicle/core'

interface MigrationStep {
  id: string
  description: string
  check: (loreDir: string) => boolean   // returns true if already done
  run: (root: string, loreDir: string) => void
}

const MIGRATIONS: MigrationStep[] = [
  {
    id: 'v2-index',
    description: 'Add index.md (project knowledge index)',
    check: (d) => existsSync(join(d, STORE_FILES.index)),
    run: (root, d) => {
      const name = root.split('/').pop() ?? 'project'
      const date = new Date().toISOString().slice(0, 10)
      writeFileSync(join(d, STORE_FILES.index), [
        `# Project Index`,
        ``,
        `**Project**: ${name}`,
        `**Last updated**: ${date}`,
        ``,
        `> Auto-generated by \`chronicle migrate\`. Edit freely.`,
        ``,
        `## Key Constraints`,
        ``,
        `_Add constraints here._`,
        ``,
        `## Architecture`,
        ``,
        `_Describe the high-level structure._`,
        ``,
      ].join('\n'))
    },
  },
  {
    id: 'v3-cache-rename',
    description: 'Rename .cache.json → .extraction-cache.json',
    check: (d) => {
      // Already done if .cache.json doesn't exist, or .extraction-cache.json already present
      const old = join(d, '.cache.json')
      const next = join(d, '.extraction-cache.json')
      return !existsSync(old) || existsSync(next)
    },
    run: (_root, d) => {
      const old = join(d, '.cache.json')
      const next = join(d, '.extraction-cache.json')
      if (existsSync(old) && !existsSync(next)) {
        renameSync(old, next)
      }
    },
  },
  {
    id: 'v4-low-confidence',
    description: 'Add low-confidence.md placeholder',
    check: (d) => existsSync(join(d, STORE_FILES['low-confidence'])),
    run: (_root, d) => {
      writeFileSync(join(d, STORE_FILES['low-confidence']), [
        `# Low-Confidence Decisions`,
        ``,
        `_Decisions extracted with confidence < 0.5 are stored here._`,
        `_Review and promote to decisions.md or discard as appropriate._`,
        ``,
      ].join('\n'))
    },
  },
  {
    id: 'v4-risks',
    description: 'Add risks.md placeholder',
    check: (d) => existsSync(join(d, STORE_FILES.risks)),
    run: (_root, d) => {
      writeFileSync(join(d, STORE_FILES.risks), [
        `# Risk Register`,
        ``,
        `_Technical and architectural risks identified from git history._`,
        ``,
      ].join('\n'))
    },
  },
  {
    id: 'v5-extraction-cache-format',
    description: 'Validate .extraction-cache.json is an object (not array)',
    check: (d) => {
      const p = join(d, '.extraction-cache.json')
      if (!existsSync(p)) return true
      try {
        const data = JSON.parse(readFileSync(p, 'utf8'))
        return !Array.isArray(data)
      } catch {
        return true  // corrupt cache — leave to doctor
      }
    },
    run: (_root, d) => {
      const p = join(d, '.extraction-cache.json')
      if (!existsSync(p)) return
      try {
        const data = JSON.parse(readFileSync(p, 'utf8'))
        if (Array.isArray(data)) {
          // Convert array format to object keyed by hash
          const obj: Record<string, unknown> = {}
          for (const entry of data) {
            if (entry?.hash) obj[entry.hash] = entry
          }
          writeFileSync(p, JSON.stringify(obj, null, 2))
        }
      } catch { /* corrupt — leave to doctor */ }
    },
  },
]

export async function cmdMigrate(opts: { dryRun?: boolean; json?: boolean }) {
  const root = findLoreRoot()

  if (!root) {
    const msg = '.lore/ not found — run `chronicle init` first'
    if (opts.json) console.log(JSON.stringify({ success: false, message: msg, steps: [] }))
    else console.error(chalk.red(`✗  ${msg}`))
    process.exit(1)
  }

  const loreDir = lorePath(root)
  const results: Array<{ id: string; description: string; status: 'skipped' | 'applied' | 'dry-run' }> = []

  let applied = 0

  for (const step of MIGRATIONS) {
    const alreadyDone = step.check(loreDir)
    if (alreadyDone) {
      results.push({ id: step.id, description: step.description, status: 'skipped' })
      continue
    }

    if (opts.dryRun) {
      results.push({ id: step.id, description: step.description, status: 'dry-run' })
      applied++
      continue
    }

    step.run(root, loreDir)
    results.push({ id: step.id, description: step.description, status: 'applied' })
    applied++
  }

  if (opts.json) {
    console.log(JSON.stringify({ success: true, applied, dryRun: opts.dryRun ?? false, steps: results }, null, 2))
    return
  }

  console.log(chalk.bold('\n◆ Chronicle Migrate\n'))

  for (const r of results) {
    if (r.status === 'skipped') {
      console.log(`  ${chalk.dim('─')}  ${chalk.dim(r.description.padEnd(50))} ${chalk.dim('already up-to-date')}`)
    } else if (r.status === 'dry-run') {
      console.log(`  ${chalk.yellow('~')}  ${r.description.padEnd(50)} ${chalk.yellow('would apply')}`)
    } else {
      console.log(`  ${chalk.green('✓')}  ${r.description.padEnd(50)} ${chalk.green('applied')}`)
    }
  }

  if (applied === 0) {
    console.log(chalk.green('\n  .lore/ is already at the current schema — nothing to do.'))
  } else if (opts.dryRun) {
    console.log(chalk.yellow(`\n  ${applied} migration(s) pending. Run \`chronicle migrate\` to apply.`))
  } else {
    console.log(chalk.green(`\n  ${applied} migration(s) applied. Run \`chronicle doctor\` to verify.`))
  }
}
