import { execSync } from 'child_process'
import { readStore, writeStore, lorePath } from './store.js'
import { readFileSync, existsSync } from 'fs'
import { join } from 'path'

export interface Era {
  tag: string            // git tag name (or 'HEAD' for current)
  fromTag: string        // previous tag (or '' for genesis)
  fromDate: string       // ISO date
  toDate: string         // ISO date (or 'present')
  decisions: EraDecision[]
  rejections: string[]
  keyFiles: string[]     // most-changed files in this era
  summary?: string       // LLM-written or manually added
}

export interface EraDecision {
  title: string
  risk: 'low' | 'medium' | 'high'
  isDeep: boolean
}

// Build the full evolution record from git tags + .lore/ store
export function buildEvolution(root: string): Era[] {
  let tags = getTagsChronological(root)

  if (tags.length === 0) {
    // No git tags — synthesize quarterly eras from commit history
    tags = buildTimeBasedEras(root)
    if (tags.length === 0) return []
  } else {
    // Add a synthetic "current" era if HEAD has commits beyond the last tag
    const latestTag = tags[tags.length - 1]
    if (isHeadAheadOfTag(root, latestTag.name)) {
      const headDate = getHeadDate(root) ?? new Date().toISOString()
      tags.push({ name: 'HEAD (current)', date: headDate, hash: 'HEAD' })
    }
  }

  const eras: Era[] = []
  for (let i = 0; i < tags.length; i++) {
    const current = tags[i]
    const previous = tags[i - 1]

    const fromTag  = previous?.name ?? ''
    const fromDate = previous?.date ?? getFirstCommitDate(root)
    const toDate   = current.name === 'HEAD (current)' ? 'present' : current.date

    const decisions = getDecisionsInRange(root, fromDate, toDate)
    const rejections = getRejectionsInRange(root, fromDate, toDate)
    const keyFiles = getKeyFilesInRange(root, previous?.hash ?? '', current.hash)

    eras.push({
      tag: current.name,
      fromTag,
      fromDate,
      toDate,
      decisions,
      rejections,
      keyFiles,
    })
  }

  return eras
}

// Render eras to the evolution.md format
export function renderEvolutionMarkdown(eras: Era[], projectName = 'Project'): string {
  const lines: string[] = [
    `# ${projectName} — System Evolution`,
    '',
    `> Auto-generated by Chronicle. Edit \`summary:\` fields to add context.`,
    '',
  ]

  for (const era of eras) {
    const range = era.fromTag
      ? `${era.fromTag} → ${era.tag}`
      : `Genesis → ${era.tag}`

    lines.push(`## Era: ${range} | ${era.fromDate.slice(0, 10)} – ${era.toDate === 'present' ? 'present' : era.toDate.slice(0, 10)}`)
    lines.push('')

    if (era.summary) {
      lines.push(`> ${era.summary}`)
      lines.push('')
    }

    if (era.decisions.length) {
      lines.push(`**Decisions (${era.decisions.length}):**`)
      for (const d of era.decisions) {
        const riskMark = d.risk === 'high' ? ' ⚠' : d.risk === 'medium' ? ' ~' : ''
        const deepMark = d.isDeep ? ' [ADR]' : ''
        lines.push(`- ${d.title}${riskMark}${deepMark}`)
      }
      lines.push('')
    }

    if (era.rejections.length) {
      lines.push(`**Rejected approaches (${era.rejections.length}):**`)
      for (const r of era.rejections) lines.push(`- ${r}`)
      lines.push('')
    }

    if (era.keyFiles.length) {
      lines.push(`**Most changed files:**`)
      for (const f of era.keyFiles.slice(0, 5)) lines.push(`- \`${f}\``)
      lines.push('')
    }

    lines.push('---', '')
  }

  return lines.join('\n')
}

// Preserve any manually-written summary: fields when regenerating
export function mergeWithExisting(newMd: string, existingMd: string): string {
  // Extract manual summaries keyed by era heading
  const summaryRe = /^## Era: (.+?)\n+> (.+?)$/gm
  const manualSummaries = new Map<string, string>()
  let m
  while ((m = summaryRe.exec(existingMd)) !== null) {
    manualSummaries.set(m[1].trim(), m[2].trim())
  }

  if (manualSummaries.size === 0) return newMd

  // Re-inject summaries into new markdown
  return newMd.replace(/^## Era: (.+?)$/gm, (match, heading) => {
    const summary = manualSummaries.get(heading.trim())
    return summary ? `${match}\n\n> ${summary}` : match
  })
}

// ── git helpers ───────────────────────────────────────────────────────────────

interface TagEntry { name: string; date: string; hash: string }

/**
 * When no git tags exist, synthesize eras from commit density.
 * Splits history into up to 4 time buckets (quarters) so evolution.md
 * always has meaningful structure even in untagged repos.
 */
function buildTimeBasedEras(root: string): TagEntry[] {
  try {
    const raw = execSync(
      `git -C "${root}" log --reverse --format="%H|%ai"`,
      { maxBuffer: 4 * 1024 * 1024 }
    ).toString().trim()
    if (!raw) return []

    const commits = raw.split('\n').filter(Boolean).map(line => {
      const [hash, ...rest] = line.split('|')
      return { hash, date: rest.join('|').trim() }
    })

    if (commits.length === 0) return []
    if (commits.length === 1) {
      return [{ name: 'v0.1 (initial)', date: commits[0].date, hash: commits[0].hash }]
    }

    // Determine bucket count: 1 bucket per ~50 commits, max 4
    const bucketCount = Math.min(4, Math.max(1, Math.floor(commits.length / 50)))
    const bucketSize = Math.floor(commits.length / bucketCount)

    return Array.from({ length: bucketCount }, (_, i) => {
      const isLast = i === bucketCount - 1
      const idx = isLast ? commits.length - 1 : (i + 1) * bucketSize - 1
      const commit = commits[idx]
      const label = `phase-${i + 1}`
      return { name: label, date: commit.date, hash: commit.hash }
    })
  } catch { return [] }
}

function getTagsChronological(root: string): TagEntry[] {
  try {
    const raw = execSync(
      `git -C "${root}" tag -l --sort=creatordate --format="%(refname:short)|%(creatordate:iso)|%(objectname:short)"`,
      { maxBuffer: 1024 * 1024 }
    ).toString()
    return raw.split('\n').filter(Boolean).map(line => {
      const [name, date, hash] = line.split('|')
      return { name, date: date?.trim() ?? '', hash }
    })
  } catch { return [] }
}

function getFirstCommitDate(root: string): string {
  try {
    return execSync(`git -C "${root}" log --reverse --format="%ai" | head -1`)
      .toString().trim()
  } catch { return '' }
}

function getHeadDate(root: string): string | null {
  try {
    return execSync(`git -C "${root}" log -1 --format="%ai"`).toString().trim() || null
  } catch { return null }
}

// Returns true if there are commits on HEAD that are not reachable from the tag
function isHeadAheadOfTag(root: string, tagName: string): boolean {
  try {
    const count = execSync(
      `git -C "${root}" rev-list --count "${tagName}..HEAD"`,
      { stdio: ['pipe', 'pipe', 'ignore'] }
    ).toString().trim()
    return parseInt(count, 10) > 0
  } catch { return false }
}

// Parse decisions.md to find entries between two dates
function getDecisionsInRange(root: string, fromDate: string, toDate: string): EraDecision[] {
  const decisionsDir = join(lorePath(root), 'decisions')
  const index = readStore(root, 'decisions')
  const rows = index.split('\n').filter(l => l.startsWith('|') && !l.includes('---') && !l.includes('Decision'))

  return rows.map(row => {
    const cols = row.split('|').map(c => c.trim()).filter(Boolean)
    return {
      title: cols[0] ?? '',
      risk: (cols[2] ?? 'low') as EraDecision['risk'],
      isDeep: row.includes('[→]') || row.includes('[→]('),
    }
  }).filter(d => d.title)
  // Note: date-range filtering would require storing dates in decisions.md rows
  // For v1, return all decisions (era grouping comes from tags in practice)
}

// Parse rejected.md to extract rejection titles
function getRejectionsInRange(root: string, fromDate: string, toDate: string): string[] {
  const content = readStore(root, 'rejected')
  const titleRe = /^## (.+?) — rejected/gm
  const titles: string[] = []
  let m
  while ((m = titleRe.exec(content)) !== null) titles.push(m[1])
  return titles
}

// Get most-changed files in a git range
function getKeyFilesInRange(root: string, fromHash: string, toHash: string): string[] {
  if (!fromHash) return []
  try {
    const range = `${fromHash}..${toHash === 'HEAD' ? 'HEAD' : toHash}`
    const raw = execSync(
      `git -C "${root}" diff --stat ${range} --name-only`,
      { maxBuffer: 1024 * 1024 }
    ).toString()
    return raw.split('\n')
      .filter(l => l.trim() && !l.includes('node_modules') && !l.includes('.lore'))
      .slice(0, 10)
  } catch { return [] }
}
