import { execSync } from 'child_process'
import { readStore, writeStore, lorePath } from './store.js'
import { readFileSync, existsSync } from 'fs'

export interface Era {
  tag: string            // git tag name (or 'HEAD' for current)
  fromTag: string        // previous tag (or '' for genesis)
  fromDate: string       // ISO date
  toDate: string         // ISO date (or 'present')
  decisions: EraDecision[]
  rejections: string[]
  keyFiles: string[]     // most-changed files in this era
  summary?: string       // LLM-written or manually added
}

export interface EraDecision {
  title: string
  risk: 'low' | 'medium' | 'high'
  isDeep: boolean
}

// Build the full evolution record from git tags + .lore/ store
export function buildEvolution(root: string): Era[] {
  let tags = getTagsChronological(root)

  if (tags.length === 0) {
    // No git tags — synthesize quarterly eras from commit history
    tags = buildTimeBasedEras(root)
    if (tags.length === 0) return []
  } else {
    // Add a synthetic "current" era if HEAD has commits beyond the last tag
    const latestTag = tags[tags.length - 1]
    if (isHeadAheadOfTag(root, latestTag.name)) {
      const headDate = getHeadDate(root) ?? new Date().toISOString()
      tags.push({ name: 'HEAD (current)', date: headDate, hash: 'HEAD' })
    }
  }

  const eras: Era[] = []
  for (let i = 0; i < tags.length; i++) {
    const current = tags[i]
    const previous = tags[i - 1]

    const fromTag  = previous?.name ?? ''
    const fromDate = previous?.date ?? getFirstCommitDate(root)
    const toDate   = current.name === 'HEAD (current)' ? 'present' : current.date

    const isFirst = i === 0
    const decisions = getDecisionsInRange(root, fromDate, toDate, isFirst)
    const rejections = getRejectionsInRange(root, fromDate, toDate, isFirst)
    const keyFiles = getKeyFilesInRange(root, previous?.hash ?? '', current.hash)

    eras.push({
      tag: current.name,
      fromTag,
      fromDate,
      toDate,
      decisions,
      rejections,
      keyFiles,
    })
  }

  return eras
}

// Render eras to the evolution.md format
export function renderEvolutionMarkdown(eras: Era[], projectName = 'Project'): string {
  const lines: string[] = [
    `# ${projectName} — System Evolution`,
    '',
    `> Auto-generated by Chronicle. Edit \`summary:\` fields to add context.`,
    '',
  ]

  for (const era of eras) {
    const range = era.fromTag
      ? `${era.fromTag} → ${era.tag}`
      : `Genesis → ${era.tag}`

    lines.push(`## Era: ${range} | ${era.fromDate.slice(0, 10)} – ${era.toDate === 'present' ? 'present' : era.toDate.slice(0, 10)}`)
    lines.push('')

    if (era.summary) {
      lines.push(`> ${era.summary}`)
      lines.push('')
    }

    if (era.decisions.length) {
      // Sort high-risk decisions first so the most impactful changes lead
      const riskPriority = { high: 0, medium: 1, low: 2 }
      const sortedDecisions = [...era.decisions].sort((a, b) => riskPriority[a.risk] - riskPriority[b.risk])
      lines.push(`**Decisions (${sortedDecisions.length}):**`)
      for (const d of sortedDecisions) {
        const riskMark = d.risk === 'high' ? ' ⚠' : d.risk === 'medium' ? ' ~' : ''
        const deepMark = d.isDeep ? ' [ADR]' : ''
        lines.push(`- ${d.title}${riskMark}${deepMark}`)
      }
      lines.push('')
    }

    if (era.rejections.length) {
      lines.push(`**Rejected approaches (${era.rejections.length}):**`)
      for (const r of era.rejections) lines.push(`- ${r}`)
      lines.push('')
    }

    // Only show key files when there are no decisions — file churn without decisions is noise
    if (era.keyFiles.length && era.decisions.length === 0) {
      lines.push(`**Most changed files:**`)
      for (const f of era.keyFiles.slice(0, 5)) lines.push(`- \`${f}\``)
      lines.push('')
    }

    lines.push('---', '')
  }

  return lines.join('\n')
}

// Preserve any manually-written summary: fields when regenerating
export function mergeWithExisting(newMd: string, existingMd: string): string {
  // Extract manual summaries keyed by era heading
  const summaryRe = /^## Era: (.+?)\n+> (.+?)$/gm
  const manualSummaries = new Map<string, string>()
  let m
  while ((m = summaryRe.exec(existingMd)) !== null) {
    manualSummaries.set(m[1].trim(), m[2].trim())
  }

  if (manualSummaries.size === 0) return newMd

  // Re-inject summaries into new markdown
  return newMd.replace(/^## Era: (.+?)$/gm, (match, heading) => {
    const summary = manualSummaries.get(heading.trim())
    return summary ? `${match}\n\n> ${summary}` : match
  })
}

// ── git helpers ───────────────────────────────────────────────────────────────

interface TagEntry { name: string; date: string; hash: string }

/**
 * When no git tags exist, synthesize eras from commit density.
 * Splits history into up to 4 time buckets (quarters) so evolution.md
 * always has meaningful structure even in untagged repos.
 */
function buildTimeBasedEras(root: string): TagEntry[] {
  try {
    const raw = execSync(
      `git -C "${root}" log --reverse --format="%H|%ai"`,
      { maxBuffer: 4 * 1024 * 1024 }
    ).toString().trim()
    if (!raw) return []

    const commits = raw.split('\n').filter(Boolean).map(line => {
      const [hash, ...rest] = line.split('|')
      return { hash, date: rest.join('|').trim() }
    })

    if (commits.length === 0) return []
    if (commits.length === 1) {
      return [{ name: 'v0.1 (initial)', date: commits[0].date, hash: commits[0].hash }]
    }

    // Determine bucket count: 1 bucket per ~50 commits, max 4
    const bucketCount = Math.min(4, Math.max(1, Math.floor(commits.length / 50)))
    const bucketSize = Math.floor(commits.length / bucketCount)

    return Array.from({ length: bucketCount }, (_, i) => {
      const isLast = i === bucketCount - 1
      const idx = isLast ? commits.length - 1 : (i + 1) * bucketSize - 1
      const commit = commits[idx]
      const label = `phase-${i + 1}`
      return { name: label, date: commit.date, hash: commit.hash }
    })
  } catch { return [] }
}

function getTagsChronological(root: string): TagEntry[] {
  try {
    const raw = execSync(
      `git -C "${root}" tag -l --sort=creatordate --format="%(refname:short)|%(creatordate:iso)|%(objectname:short)"`,
      { maxBuffer: 1024 * 1024 }
    ).toString()
    return raw.split('\n').filter(Boolean).map(line => {
      const [name, date, hash] = line.split('|')
      return { name, date: date?.trim() ?? '', hash }
    })
  } catch { return [] }
}

function getFirstCommitDate(root: string): string {
  try {
    return execSync(`git -C "${root}" log --reverse --format="%ai" | head -1`)
      .toString().trim()
  } catch { return '' }
}

function getHeadDate(root: string): string | null {
  try {
    return execSync(`git -C "${root}" log -1 --format="%ai"`).toString().trim() || null
  } catch { return null }
}

// Returns true if there are commits on HEAD that are not reachable from the tag
function isHeadAheadOfTag(root: string, tagName: string): boolean {
  try {
    const count = execSync(
      `git -C "${root}" rev-list --count "${tagName}..HEAD"`,
      { stdio: ['pipe', 'pipe', 'ignore'] }
    ).toString().trim()
    return parseInt(count, 10) > 0
  } catch { return false }
}

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/

// Parse decisions.md to find entries within a date range.
// Handles both old format (no date column) and new format (date in first column).
//
// isFirst: true for the genesis era — uses inclusive lower bound (date >= from).
// Subsequent eras use exclusive lower bound (date > from) so a decision that shares
// its date with an era boundary only ever appears in the FIRST era of that date,
// not in every era that spans that same day.
function getDecisionsInRange(root: string, fromDate: string, toDate: string, isFirst = false): EraDecision[] {
  const index = readStore(root, 'decisions')
  // Exclude separator rows and the header row (first cell is 'Date' or 'Decision')
  const rows = index.split('\n').filter(l => {
    if (!l.startsWith('|') || l.includes('---')) return false
    const firstCell = l.split('|')[1]?.trim() ?? ''
    return firstCell !== 'Date' && firstCell !== 'Decision'
  })

  const from = fromDate.slice(0, 10)
  const to = toDate === 'present' ? '9999-99-99' : toDate.slice(0, 10)

  return rows.map(row => {
    const cols = row.split('|').map(c => c.trim()).filter(Boolean)
    if (cols.length < 2) return null

    // Detect format: new format has a date in col[0], old format has title in col[0]
    const hasDate = DATE_RE.test(cols[0])
    const date = hasDate ? cols[0] : ''
    const rawTitle = hasDate ? (cols[1] ?? '') : (cols[0] ?? '')
    const title = rawTitle.replace(/<!--.*?-->/g, '').replace(/\[→\]\([^)]+\)/g, '').trim()
    const risk = ((hasDate ? cols[3] : cols[2]) ?? 'low') as EraDecision['risk']

    if (date) {
      // Genesis era: inclusive lower bound — decisions ON the start date belong here.
      // Later eras: exclusive lower bound — date must be strictly AFTER fromDate so
      // decisions with the same date as a tag boundary don't flood every subsequent era.
      const afterFrom = isFirst ? date >= from : date > from
      if (!afterFrom || (to !== '9999-99-99' && date > to)) return null
    }

    return title ? { title, risk, isDeep: row.includes('[→]') } : null
  }).filter((d): d is EraDecision => d !== null)
}

// Parse rejected.md to extract rejection titles within a date range.
// Entries have the form: `## Title — rejected (YYYY-MM-DD)`
function getRejectionsInRange(root: string, fromDate: string, toDate: string, isFirst = false): string[] {
  const content = readStore(root, 'rejected')
  const entryRe = /^## (.+?) — rejected \((\d{4}-\d{2}-\d{2})\)/gm
  const noDateRe = /^## (.+?) — rejected$/gm

  const from = fromDate.slice(0, 10)
  const to = toDate === 'present' ? '9999-99-99' : toDate.slice(0, 10)

  const titles: string[] = []
  let m

  // Entries with dates: apply same exclusive-lower-bound logic as decisions
  while ((m = entryRe.exec(content)) !== null) {
    const [, title, date] = m
    const afterFrom = isFirst ? date >= from : date > from
    if (afterFrom && (to === '9999-99-99' || date <= to)) titles.push(title)
  }

  // Entries without dates (legacy format): include only in the genesis era
  if (isFirst) {
    while ((m = noDateRe.exec(content)) !== null) titles.push(m[1])
  }

  return titles
}

// Get most-changed files in a git range
function getKeyFilesInRange(root: string, fromHash: string, toHash: string): string[] {
  if (!fromHash) return []
  try {
    const range = `${fromHash}..${toHash === 'HEAD' ? 'HEAD' : toHash}`
    const raw = execSync(
      `git -C "${root}" diff --stat ${range} --name-only`,
      { maxBuffer: 1024 * 1024 }
    ).toString()
    return raw.split('\n')
      .filter(l => l.trim() && !l.includes('node_modules') && !l.includes('.lore'))
      .slice(0, 10)
  } catch { return [] }
}
