import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs'
import { join } from 'path'
import chalk from 'chalk'

export type ToolName =
  | 'claude-code'
  | 'cursor'
  | 'aider'
  | 'gemini-cli'
  | 'copilot'
  | 'codex'
  | 'opencode'
  | 'trae'
  | 'factory'
  | 'openclaw'

export interface AdapterResult {
  tool: ToolName
  filesWritten: string[]
  instructions: string
}

// Each adapter writes the tool-specific config and returns what was created
const ADAPTERS: Record<ToolName, (root: string) => AdapterResult> = {
  'claude-code': adapterClaudeCode,
  'cursor':      adapterCursor,
  'aider':       adapterAider,
  'gemini-cli':  adapterGeminiCLI,
  'copilot':     adapterCopilot,
  'codex':       adapterCodex,
  'opencode':    adapterOpenCode,
  'trae':        adapterGenericPipe('trae'),
  'factory':     adapterGenericPipe('factory'),
  'openclaw':    adapterClaudeCode,  // same MCP protocol as Claude Code
}

export function installAdapter(root: string, tool: ToolName): AdapterResult {
  return ADAPTERS[tool](root)
}

export const ALL_TOOLS = Object.keys(ADAPTERS) as ToolName[]

// ── Claude Code ───────────────────────────────────────────────────────────────
function adapterClaudeCode(root: string): AdapterResult {
  const claudeDir = join(root, '.claude')
  mkdirSync(claudeDir, { recursive: true })

  // Claude Code MCP config — .claude/mcp.json (project-scoped)
  const mcpPath = join(claudeDir, 'mcp.json')
  const mcp = existsSync(mcpPath)
    ? JSON.parse(readFileSync(mcpPath, 'utf8'))
    : { mcpServers: {} }
  // Support both old (servers) and new (mcpServers) format
  const key = mcp.mcpServers !== undefined ? 'mcpServers' : 'servers'
  mcp[key] = mcp[key] ?? {}
  mcp[key].chronicle = { command: 'chronicle', args: ['mcp'] }
  writeFileSync(mcpPath, JSON.stringify(mcp, null, 2))

  // Hooks — merge with existing settings.json
  const settingsPath = join(claudeDir, 'settings.json')
  const settings = existsSync(settingsPath)
    ? JSON.parse(readFileSync(settingsPath, 'utf8'))
    : {}
  settings.hooks = {
    ...settings.hooks,
    SessionStart: [
      ...(settings.hooks?.SessionStart ?? []),
      { matcher: '', hooks: [{ type: 'command', command: 'chronicle inject --format=markdown 2>/dev/null || true' }] },
    ],
  }
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2))

  return {
    tool: 'claude-code',
    filesWritten: [mcpPath, settingsPath],
    instructions: `MCP server + hooks installed. Run \`claude mcp list\` to verify chronicle is registered.`,
  }
}

// ── Cursor ────────────────────────────────────────────────────────────────────
function adapterCursor(root: string): AdapterResult {
  const rulesPath = join(root, '.cursorrules')
  const context = buildInjectContent(root)

  const content = `# Chronicle — AI development memory
# Auto-generated by \`chronicle hooks\`. Re-run to refresh.
# Source of truth: .lore/ directory

${context}

---
# Chronicle instructions
When making architectural decisions, note them as:
  DECISION: <what> | BECAUSE: <why> | AFFECTS: <files>
When abandoning an approach, note:
  REJECTED: <what> | REASON: <why>
`
  writeFileSync(rulesPath, content)

  // Also set up a post-commit hook that refreshes .cursorrules
  return {
    tool: 'cursor',
    filesWritten: [rulesPath],
    instructions: `.cursorrules written with current Chronicle context.\nRe-run \`chronicle hooks install --tool=cursor\` to keep it fresh, or add to post-commit hook.`,
  }
}

// ── Aider ─────────────────────────────────────────────────────────────────────
function adapterAider(root: string): AdapterResult {
  // Aider reads files passed with --read; generate a .aider.conf.yml
  const confPath = join(root, '.aider.conf.yml')
  const existing = existsSync(confPath) ? readFileSync(confPath, 'utf8') : ''

  const MARKER = '# chronicle-managed'
  if (!existing.includes(MARKER)) {
    const addition = `\n${MARKER}\n# Chronicle context files (AI development memory)\nread:\n  - .lore/index.md\n  - .lore/decisions.md\n  - .lore/rejected.md\n`
    writeFileSync(confPath, existing + addition)
  }

  return {
    tool: 'aider',
    filesWritten: [confPath],
    instructions: `.aider.conf.yml updated.\nAider will automatically read .lore/ context files on every session.`,
  }
}

// ── Gemini CLI ────────────────────────────────────────────────────────────────
function adapterGeminiCLI(root: string): AdapterResult {
  const geminiPath = join(root, 'GEMINI.md')
  const context = buildInjectContent(root)

  writeFileSync(geminiPath, `# Project Context (Chronicle)\n\n${context}\n`)

  return {
    tool: 'gemini-cli',
    filesWritten: [geminiPath],
    instructions: `GEMINI.md written. Gemini CLI loads this automatically as project context.`,
  }
}

// ── GitHub Copilot ────────────────────────────────────────────────────────────
function adapterCopilot(root: string): AdapterResult {
  const githubDir = join(root, '.github')
  mkdirSync(githubDir, { recursive: true })
  const instrPath = join(githubDir, 'copilot-instructions.md')
  const context = buildInjectContent(root)

  writeFileSync(instrPath, `# Copilot Instructions (Chronicle)\n\n${context}\n`)

  return {
    tool: 'copilot',
    filesWritten: [instrPath],
    instructions: `.github/copilot-instructions.md written. Copilot reads this as workspace context.`,
  }
}

// ── Codex ─────────────────────────────────────────────────────────────────────
function adapterCodex(root: string): AdapterResult {
  const instrPath = join(root, 'AGENTS.md')
  const context = buildInjectContent(root)

  const content = existsSync(instrPath) ? readFileSync(instrPath, 'utf8') : ''
  if (!content.includes('Chronicle')) {
    writeFileSync(instrPath, content + `\n\n## Chronicle Context\n\n${context}\n`)
  }

  return {
    tool: 'codex',
    filesWritten: [instrPath],
    instructions: `AGENTS.md updated with Chronicle context.\nOr pipe directly: chronicle inject | codex`,
  }
}

// ── OpenCode ──────────────────────────────────────────────────────────────────
function adapterOpenCode(root: string): AdapterResult {
  const confPath = join(root, '.opencode.json')
  const conf = existsSync(confPath)
    ? JSON.parse(readFileSync(confPath, 'utf8'))
    : {}

  conf.contextFiles = [
    ...(conf.contextFiles ?? []),
    '.lore/index.md',
    '.lore/decisions.md',
    '.lore/rejected.md',
  ].filter((v, i, a) => a.indexOf(v) === i)  // dedupe

  writeFileSync(confPath, JSON.stringify(conf, null, 2))

  return {
    tool: 'opencode',
    filesWritten: [confPath],
    instructions: `.opencode.json updated with Chronicle context files.`,
  }
}

// ── Generic pipe adapter (Trae, Factory, etc.) ────────────────────────────────
function adapterGenericPipe(tool: ToolName) {
  return (root: string): AdapterResult => ({
    tool,
    filesWritten: [],
    instructions: `${tool} uses the universal pipe interface:\n  chronicle inject | ${tool} "<your prompt>"`,
  })
}

// ── helpers ───────────────────────────────────────────────────────────────────

function buildInjectContent(root: string): string {
  // Read the store directly (no subprocess needed)
  const { readStore, lorePath } = require('@chronicle/core')
  const parts: string[] = []

  const index = readStore(root, 'index')
  if (index) parts.push(index)
  parts.push(readStore(root, 'decisions'))
  parts.push(readStore(root, 'rejected'))

  return parts.filter(Boolean).join('\n\n---\n\n')
}
